Elev_Matrix_Output_file_path = "GeoGraphicaPr/database/Elev_Matrix_Output.xlsx"
EGM96_csv_file_path = "GeoGraphicaPr/database/EGM96.csv"

base_path = "GeoGraphicaPr/sources/final_phase/all_sources/project_result_csv_files/new/python"

TxxParker_file_name = "TxxParker.csv"
TxyParker_file_name = "TxyParker.csv"
TxzParker_file_name = "TxzParker.csv"
TyyParker_file_name = "TyyParker.csv"
TyzParker_file_name = "TyzParker.csv"
TzzParker_file_name = "TzzParker.csv"
allTparker_file_name = "Gravity Gradient Parker.csv"

TxxEGM96_file_name = "TxxEGM96.csv"
TxyEGM96_file_name = "TxyEGM96.csv"
TxzEGM96_file_name = "TxzEGM96.csv"
TyyEGM96_file_name = "TyyEGM96.csv"
TyzEGM96_file_name = "TyzEGM96.csv"
TzzEGM96_file_name = "TzzEGM96.csv"
allTEGM96_file_name = "Gravity Gradient EGM96.csv"

TxxTOTAL_file_name = "TxxTOTAL.csv"
TxyTOTAL_file_name = "TxyTOTAL.csv"
TxzTOTAL_file_name = "TxzTOTAL.csv"
TyyTOTAL_file_name = "TyyTOTAL.csv"
TyzTOTAL_file_name = "TyzTOTAL.csv"
TzzTOTAL_file_name = "TzzTOTAL.csv"
allTTOTAL_file_name = "Gravity Gradient TOTAL.csv"
